---
- name: Temporarily Install Required Packages
  vars:
    required_packages:
      - e2fsprogs
      - lvm2
      - parted
      - xfsprogs
  block:
    - name: Get Installed Packages
      ansible.builtin.package_facts:
        manager: auto
        strategy: all

    - name: Get Missing Packages
      ansible.builtin.set_fact:
        missing_packages: "{{ required_packages | difference(ansible_facts.packages.keys() | list) }}"

    - name: Install Missing Packages
      become: true
      when: missing_packages | length > 0
      ansible.builtin.package:
        name: "{{ missing_packages }}"
        state: present

- name: Create Disk Symlink Map
  block:
    - name: Get Cloud-Init Signature
      become: true
      ansible.builtin.command: cloud-id
      changed_when: false
      register: cloud_id

    - name: Get Virtualization Engine
      become: true
      ansible.builtin.command: systemd-detect-virt
      changed_when: false
      register: virtualization_engine

    - name: Get Disk Devices
      ansible.builtin.command: lsblk -Jo PATH,SERIAL,TYPE
      changed_when: false
      register: devices

    - name: Create Symlink Map
      ansible.builtin.set_fact:
        symlink_map: "{{ devices.stdout | from_json | to_symlink_map(cloud_id.stdout, virtualization_engine.stdout) }}"

    - name: Print Symlink Map
      ansible.builtin.debug:
        var: symlink_map

- name: Create Logical Volumes Iterable
  ansible.builtin.set_fact:
    lvs: "{{ data_vdisks | to_lvs }}"
